services:
  bima-postgres:
    image: postgres:15-alpine
    container_name: bima-postgres
    restart: always
    environment:
      POSTGRES_USER: bima
      POSTGRES_PASSWORD: bimapassword
      POSTGRES_DB: bima_db
    ports:
      - "54322:5432"
    volumes:
      - bima_postgres_data:/var/lib/postgresql/data
    networks:
      - bima-net

  bima-backend:
    build:
      context: apps/api
      dockerfile: Dockerfile
    image: itsanla/bima:1.0.1
    container_name: bima-backend
    restart: always
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - PORT=8081
      - DATABASE_URL=postgresql://bima:bimapassword@bima-postgres:5432/bima_db?schema=public&sslmode=disable
    networks:
      - bima-net
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bima-api.rule=Host(`api.steamlog.cloud`)"
      - "traefik.http.services.bima-api.loadbalancer.server.port=8081"
      - "traefik.http.routers.bima-api.tls.certresolver=letsencrypt"
    depends_on:
      - bima-postgres

  bima-pgweb:
    image: sosedoff/pgweb
    container_name: bima-pgweb
    restart: always
    environment:
      - DATABASE_URL=postgres://bima:bimapassword@bima-postgres:5432/bima_db?sslmode=disable
    ports:
      - "8082:8081"
    networks:
      - bima-net
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bima-pgweb.rule=Host(`db.steamlog.cloud`)"
      - "traefik.http.services.bima-pgweb.loadbalancer.server.port=8081"
      - "traefik.http.routers.bima-pgweb.tls.certresolver=letsencrypt"
    depends_on:
      - bima-postgres

volumes:
  bima_postgres_data:

networks:
  bima-net:
  coolify:
    external: true
