version: '3.8'

services:
  bima-api:
    build: .
    container_name: bima-backend-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_DIR=/app/data
    volumes:
      # Gunakan Named Volumes agar Coolify menyimpannya secara permanen dan aman
      - bima_data:/app/data
      - bima_storage:/app/storage
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      # Routing untuk API
      - "traefik.http.routers.bima-api.rule=Host(`bima-version.steamlog.cloud`)"
      - "traefik.http.routers.bima-api.entrypoints=https"
      - "traefik.http.routers.bima-api.tls=true"
      - "traefik.http.routers.bima-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.bima-api.loadbalancer.server.port=3100"

networks:
  coolify:
    external: true

volumes:
  bima_data:
    name: bima_api_data
  bima_storage:
    name: bima_api_storage
