version: '3.8'

services:
  bima-api:
    build: .
    container_name: bima-backend-api
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Mount folder data dan storage dari VPS ke dalam container
      - ../data:/app/data
      - ../storage:/app/storage
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      # Routing untuk API
      - "traefik.http.routers.bima-api.rule=Host(`bima-version.steamlog.cloud`)"
      - "traefik.http.routers.bima-api.entrypoints=websecure"
      - "traefik.http.routers.bima-api.tls=true"
      - "traefik.http.services.bima-api.loadbalancer.server.port=3100"

networks:
  coolify:
    external: true
